server:
  port: 8080
info:
  app:
    version: @project.version@
spring:
  application:
    name: @project.artifactId@
  mvc:
    path match:
      matching-strategy: ant-path-matcher #https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
#  main:
##    ┌─────┐
##    |  caseVmConverter (field private com.liquibase.services.web.convert.ProfileVmConverter com.liquibase.services.web.convert.CaseVmConverter.profileVmConverter)
##    ↑     ↓
##    |  profileVmConverter (field private com.liquibase.services.web.convert.CaseVmConverter com.liquibase.services.web.convert.ProfileVmConverter.caseVmConverter)
##    └─────┘
##    Action:
##    Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
#    allow-circular-references: true #https://www.baeldung.com/circular-dependencies-in-spring
  profiles:
    active: default
  liquibase:
    enabled: false # change to true in order to use a real db and run schema
    change-log: classpath:/liquibase/changelog-master.xml
    default-schema: netapp
  datasource:
    # for running with docker -> change the port accordingly (see docker-compose file-3366)
    url: jdbc:mysql://localhost:3306/netapp?user=${spring.datasource.username}&password=${spring.datasource.password}&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbcdriver=org.h2.Driver  #jdbcdriver=com.mysql.jdbc.Driver //deprecated drive.
      #https://docs.spring.io/spring-cloud-dataflow/docs/1.1.2.RELEASE/reference/html/configuration-rdbms.html
  jpa:
    database: h2 # change to 'mysql' in order to use a real db (like docker)
    show-sql: true
    properties:
      hibernate:
        default_schema: netapp
        connection:
          url: jdbc:h2:mem:netapp;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS netapp
#          url: jdbc:mysql://localhost:3366/netapp?user=${spring.jpa.properties.username}&password=${spring.jpa.properties.password}&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC #jdbc:h2:mem:netapp;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS netapp
      username: root
      password: administrator
#    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update #none, create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: always
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_0
  swagger-ui:
    use-root-path: true
