info:
  app:
    name: @project.artifactId@
    version: @project.version@
spring:
  server:
    port: 8086
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    default-schema: netapp
    url: jdbc:mysql://localhost:3306/netapp?useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    user: root
    password: administrator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: always
