info:
  app:
    name: @project.artifactId@
    version: @project.version@
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
#  main:
##    ┌─────┐
##    |  caseVmConverter (field private com.liquibase.services.web.convert.ProfileVmConverter com.liquibase.services.web.convert.CaseVmConverter.profileVmConverter)
##    ↑     ↓
##    |  profileVmConverter (field private com.liquibase.services.web.convert.CaseVmConverter com.liquibase.services.web.convert.ProfileVmConverter.caseVmConverter)
##    └─────┘
##    Action:
##    Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
#    allow-circular-references: true
  server:
    port: 8080
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    default-schema: netapp
  datasource:
    url: jdbc:mysql://localhost:3306/netapp?useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    user: root
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbcdriver=org.h2.Driver  #jdbcdriver=com.mysql.jdbc.Driver //deprecated drive.
      #https://docs.spring.io/spring-cloud-dataflow/docs/1.1.2.RELEASE/reference/html/configuration-rdbms.html
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: always
